replicaCount: 1

config:
  enabled: true
  data:
    ENV_AUTH_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/user_db"
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
    SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "1"
    APP_DRIVER_RESET_PASSWORD_URL: "https://driver-portal-dev.electrahub.net/reset-password"

secrets:
  existingSecretName: "auth-secrets-dev"

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_LIQUIBASE_ENABLED: "true"
  APP_DRIVER_RESET_PASSWORD_URL: "https://driver-portal-dev.electrahub.net/reset-password"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
