replicaCount: 1

config:
  enabled: true
  data:
    ENV_AUTH_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/user_db"
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
    SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "1"
    APP_DRIVER_RESET_PASSWORD_URL: "https://driver-portal-dev.electrahub.net/reset-password"
    APP_DRIVER_VERIFY_EMAIL_URL: "https://driver-portal-dev.electrahub.net/verify-email"
    APP_SECURITY_OAUTH_FACEBOOK_ENABLED: "true"
    APP_SECURITY_OAUTH_FACEBOOK_APP_ID: "2072104083371434"
    APP_SECURITY_OAUTH_FACEBOOK_AUTO_PROVISION_USERS: "true"

secrets:
  existingSecretName: "auth-secrets-dev"

extraSecretEnv:
  - name: "APP_SECURITY_OAUTH_FACEBOOK_APP_SECRET"
    secretName: "facebook-oauth-dev-secret"
    secretKey: "APP_SECURITY_OAUTH_FACEBOOK_APP_SECRET"

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_LIQUIBASE_ENABLED: "true"
  APP_DRIVER_RESET_PASSWORD_URL: "https://driver-portal-dev.electrahub.net/reset-password"
  APP_DRIVER_VERIFY_EMAIL_URL: "https://driver-portal-dev.electrahub.net/verify-email"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
