config:
  enabled: true
  data:
    ENV_AUTH_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/user_db"

secrets:
  existingSecretName: "auth-secrets-dev"

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_LIQUIBASE_ENABLED: "true"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

