fullnameOverride: "auth-service"
image:
  repository: amolsurjuse/auth-service
service:
  port: 8080
containerPort: 8080
secrets:
  env:
    ENV_AUTH_DATASOURCE_USERNAME: "ENV_AUTH_DATASOURCE_USERNAME"
    ENV_AUTH_DATASOURCE_PASSWORD: "ENV_AUTH_DATASOURCE_PASSWORD"

config:
  data:
    LOGGING_LEVEL_ROOT: "DEBUG"
    LOGGING_LEVEL_COM_ELECTRAHUB_IDENTITY: "INFO"
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "WARN"
    LOGGING_LEVEL_ORG_HIBERNATE: "WARN"
    LOGGING_LEVEL_LIQUIBASE: "INFO"
    SPRING_LIQUIBASE_ENABLED: "true"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
    SPRING_JPA_OPEN_IN_VIEW: "false"
    SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
    SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: "UTC"
    SPRING_DATA_REDIS_HOST: "redis"
    SPRING_DATA_REDIS_PORT: "6379"
    SPRING_DATA_REDIS_TIMEOUT: "2s"
    SPRING_DATA_REDIS_LETTUCE_POOL_ENABLED: "true"
    SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE: "16"
    SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE: "16"
    SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE: "2"
    SPRING_DATA_REDIS_LETTUCE_POOL_TIME_BETWEEN_EVICTION_RUNS: "30s"
    APP_SECURITY_JWT_ISSUER: "auth-service"
    APP_SECURITY_JWT_SECRET: "CHANGE_ME_TO_A_LONG_RANDOM_64+_CHAR_SECRET_CHANGE_ME"
    APP_SECURITY_JWT_ACCESS_TOKEN_TTL_MINUTES: "15"
    APP_SECURITY_JWT_REFRESH_TOKEN_TTL_DAYS: "30"
    APP_CORS_ALLOWED_ORIGIN_PATTERNS: "http://localhost:4200,http://localhost:4201,http://localhost:4211,http://localhost:8080,https://dev.electrahub.com,https://dev.electrahub.com:8443,http://driver-portal-dev.electrahub.com:8080,https://driver-portal-dev.electrahub.com,https://driver-portal-dev.electrahub.com:8443,https://driver-portal-*.electrahub.com,https://driver-portal-*.electrahub.com:*"
    APP_COOKIES_REFRESH_NAME: "__Host-rt"
    APP_COOKIES_DEVICE_NAME: "did"
    APP_COOKIES_SAME_SITE: "Strict"
    APP_CACHE_USER_DETAILS_TTL_SECONDS: "300"
    APP_REDIS_REFRESH_PREFIX: "rt:"
    APP_REDIS_REFRESH_USER_PREFIX: "rtu:"
    APP_REDIS_REFRESH_DEVICE_PREFIX: "rtd:"
    APP_REDIS_DENYLIST_PREFIX: "deny:jwt:"
    APP_REDIS_TOKEN_VERSION_PREFIX: "tv:"
    OPENAPI_ENABLED: "true"
    SPRINGDOC_API_DOCS_PATH: "/v3/api-docs"
    SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
    SPRINGDOC_SWAGGER_UI_DISABLE_DEFAULT_URL: "false"
    APP_USER_SERVICE_BASE_URL: "http://user-service:8082"
