fullnameOverride: "auth-service"
image:
  repository: amolsurjuse/auth-service
service:
  port: 8080
containerPort: 8080
secrets:
  env:
    ENV_AUTH_DATASOURCE_USERNAME: "ENV_AUTH_DATASOURCE_USERNAME"
    ENV_AUTH_DATASOURCE_PASSWORD: "ENV_AUTH_DATASOURCE_PASSWORD"
    JWT_SECRET: "JWT_SECRET"
