fullnameOverride: kafka

replicaCount: 1

image:
  repository: bitnamilegacy/kafka
  tag: "4.0.0-debian-12-r10"

kafka:
  clusterId: "smfL9D2PSy2Y1AZaZirmGg"
  numPartitions: 3
  autoCreateTopics: true
  logRetentionHours: 168
  messageMaxBytes: "1048576"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

pdb:
  enabled: false
