fullnameOverride: "payment-service"
image:
  repository: amolsurjuse/payment-service

service:
  port: 8083
containerPort: 8083

env:
  SPRING_PROFILES_ACTIVE: "dev"

config:
  data:
    SERVER_PORT: "8083"
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
    APP_CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://driver-portal-dev.electrahub.com:8080,https://driver-portal-dev.electrahub.com:8443"

readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 6

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 6

startupProbe:
  enabled: false

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
