replicaCount: 1

env:
  SPRING_PROFILES_ACTIVE: "prod"

image:
  pullPolicy: Always

resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

config:
  data:
    SUPPORT_EMAIL: "support@electrahub.com"
    AI_STREAM_TOKEN_DELAY_MS: "0"
    AI_PROVIDER: "ollama"
    AI_MODEL: "electrahub-sparky:8b"
    OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    AI_TEMPERATURE: "0.12"
    AI_MAX_OUTPUT_TOKENS: "320"
    AI_LLM_TIMEOUT_MS: "30000"
