replicaCount: 1

extraSecretEnv:
  - name: "OCPP_HANDSHAKE_SIMULATOR_PASSWORD"
    secretName: "ocpp-simulator-handshake-secret"
    secretKey: "OCPP_HANDSHAKE_SIMULATOR_PASSWORD"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
