secrets:
  existingSecretName: "postgresql-dev-secret"

extraSecretEnv:
  - name: "SPRING_DATA_REDIS_PASSWORD"
    secretName: "redis-dev-secret"
    secretKey: "redis-password"
  - name: "APP_SECURITY_INTERNAL_TOKEN"
    secretName: "electrahub-internal-service-token"
    secretKey: "APP_SECURITY_INTERNAL_TOKEN"
  - name: "APP_GATEWAY_MOLLIE_CREDENTIAL"
    secretName: "payment-gateway-provider-dev"
    secretKey: "APP_GATEWAY_MOLLIE_CREDENTIAL"
    optional: true
  - name: "APP_GATEWAY_2C2P_DEMO_SECRET_KEY"
    secretName: "payment-gateway-provider-dev"
    secretKey: "APP_GATEWAY_2C2P_DEMO_SECRET_KEY"
    optional: true

replicaCount: 1

image:
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
