replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "admin-portal-dev.electrahub.net"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false
