replicaCount: 1

env:
  JAVA_TOOL_OPTIONS: "-Xms96m -Xmx192m"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "dev.electrahub.com"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  path: /(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
