replicaCount: 1

env:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_CORS_ALLOWED_ORIGIN_PATTERNS: "https://electrahub.com,https://www.electrahub.com,https://electrahub.net,https://www.electrahub.net,https://api.electrahub.net,https://admin-portal.electrahub.net,https://driver-portal.electrahub.net,https://ocpp-simulator.electrahub.net"

extraSecretEnv:
  - name: "APP_INTERNAL_ACCESS_CONTEXT_SECRET"
    secretName: "access-context-prod-secret"
    secretKey: "APP_INTERNAL_ACCESS_CONTEXT_SECRET"
  - name: "APP_SECURITY_JWT_SECRET"
    secretName: "auth-jwt-prod-secret"
    secretKey: "APP_SECURITY_JWT_SECRET"
  - name: "SPRING_DATA_REDIS_PASSWORD"
    secretName: "redis-prod-secret"
    secretKey: "redis-password"

config:
  data:
    APP_CORS_ALLOWED_ORIGIN_PATTERNS: "https://electrahub.com,https://www.electrahub.com,https://electrahub.net,https://www.electrahub.net,https://api.electrahub.net,https://admin-portal.electrahub.net,https://driver-portal.electrahub.net,https://ocpp-simulator.electrahub.net"
    APP_HTTP_LOGGING_ENABLED: "false"
    APP_HTTP_LOGGING_INCLUDE_BODIES: "false"
    APP_HTTP_LOGGING_FULL_REQUEST_RESPONSE: "false"
    LOGGING_LEVEL_COM_ELECTRAHUB_GATEWAY: "INFO"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "api.electrahub.net"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  path: /(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secretName: "electrahub-prod-tls"

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

extraIngresses:
  - name: public-notifications
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/notifications/$2"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "10m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    rules:
      - host: "electrahub.net"
        paths:
          - path: /notifications(/|$)(.*)
            pathType: ImplementationSpecific
      - host: "www.electrahub.net"
        paths:
          - path: /notifications(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "electrahub.net"
          - "www.electrahub.net"
        secretName: "electrahub-prod-tls"
