apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.name" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: ElectraHub Prometheus
        uid: electrahub-prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.prometheus.url | quote }}
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s