replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "dev.electrahub.net"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

extraIngresses:
  - name: public-root
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    rules:
      - host: "electrahub.net"
        paths:
          - path: /
            pathType: Prefix
      - host: "www.electrahub.net"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "electrahub.net"
          - "www.electrahub.net"
        secretName: "electrahub-dev-tls"
  - name: public-org-prefix
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    rules:
      - host: "electrahub.net"
        paths:
          - path: /org-page(/|$)(.*)
            pathType: ImplementationSpecific
      - host: "www.electrahub.net"
        paths:
          - path: /org-page(/|$)(.*)
            pathType: ImplementationSpecific
      - host: "dev.electrahub.net"
        paths:
          - path: /org-page(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "electrahub.net"
          - "www.electrahub.net"
          - "dev.electrahub.net"
        secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false
