replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "dev.electrahub.com"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /org-page(/|$)(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false
