fullnameOverride: splunk

ingress:
  enabled: true
  className: nginx
  host: splunk.electrahub.net

persistence:
  size: 50Gi

resources:
  requests:
    cpu: "1"
    memory: 3Gi
  limits:
    cpu: "2"
    memory: 6Gi
