secrets:
  existingSecretName: "postgresql-dev-secret"

extraSecretEnv:
  - name: "ENV_REDIS_PASSWORD"
    secretName: "redis-dev-secret"
    secretKey: "redis-password"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
