secrets:
  existingSecretName: "postgresql-dev-secret"

replicaCount: 1

env:
  JAVA_TOOL_OPTIONS: "-Xms96m -Xmx192m"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
