secrets:
  existingSecretName: "postgresql-prod-secret"

env:
  SPRING_PROFILES_ACTIVE: "prod"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
