fullnameOverride: postgresql

image:
  repository: postgres
  tag: "16"

auth:
  existingSecretName: postgresql-dev-secret

persistence:
  size: 10Gi

postgresql:
  config:
    listen_addresses: "'*'"
    max_connections: 250

pdb:
  enabled: false
