fullnameOverride: postgresql

image:
  repository: postgres
  tag: "16"

auth:
  username: appuser
  password: devpassword
  database: appdb

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

pdb:
  enabled: false
