apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk.name" . }}
  labels:
    {{- include "splunk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "splunk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
    - name: hec
      port: {{ .Values.service.hecPort }}
      targetPort: hec
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
