apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "splunk.name" . }}
  labels:
    {{- include "splunk.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "splunk.name" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "splunk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "splunk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: splunk
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.admin.existingSecretName }}
                  key: {{ .Values.admin.passwordKey }}
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hec.existingSecretName }}
                  key: {{ .Values.hec.tokenKey }}
          ports:
            - name: web
              containerPort: 8000
            - name: hec
              containerPort: 8088
            - name: management
              containerPort: 8089
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /en-US/account/login
              port: web
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /en-US/account/login
              port: web
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /en-US/account/login
              port: web
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          volumeMounts:
            - name: splunk-var
              mountPath: /opt/splunk/var
  volumeClaimTemplates:
    - metadata:
        name: splunk-var
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
