replicaCount: 2

features:
  enabled: true
  adminApiEnabled: true
  userEventsEnabled: true

gatewayIdentitySecret:
  existingSecret: access-context-prod-secret

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi
