replicaCount: 1

image:
  repository: amolsurjuse/plug-and-charge-platform
  tag: 7f88563
  digest: sha256:208033db697376577f320558193a1749832ad77484ef5127e6a135a86f8f432e
  pullPolicy: IfNotPresent

service:
  port: 8098

database:
  existingSecret: plug-and-charge-platform-db
  urlKey: url
  usernameKey: username
  passwordKey: password

rabbitmq:
  host: rabbitmq
  port: 5672

gatewayIdentitySecret:
  existingSecret: ""
  key: APP_INTERNAL_ACCESS_CONTEXT_SECRET

features:
  enabled: false
  adminApiEnabled: false
  userEventsEnabled: false
  ocppEnabled: false
  ocpiEnabled: false
  outboxPublisherEnabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
