apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "splunk-log-collector.name" . }}
  labels:
    {{- include "splunk-log-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "splunk-log-collector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "splunk-log-collector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "splunk-log-collector.name" . }}
      containers:
        - name: vector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config", "/etc/vector/vector.yaml"]
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.splunk.existingSecretName }}
                  key: {{ .Values.splunk.tokenKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: vector-data
              mountPath: /vector-data-dir
            - name: config
              mountPath: /etc/vector
            - name: var-log
              mountPath: /var/log
              readOnly: true
            - name: var-lib-docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: vector-data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "splunk-log-collector.name" . }}-config
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker-containers
          hostPath:
            path: /var/lib/docker/containers
