secrets:
  existingSecretName: "postgresql-dev-secret"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

config:
  data:
    NOTIFICATION_CHANNEL_EMAIL_DAILY_LIMIT: "59"
    NOTIFICATION_CHANNEL_PUSH_REAL_SEND_ENABLED: "true"
    NOTIFICATION_CHANNEL_PUSH_DAILY_LIMIT: "500"
    NOTIFICATION_DRIVER_RESET_PASSWORD_URL: "https://driver-portal-dev.electrahub.net/reset-password"

extraSecretEnv:
  - name: FIREBASE_SERVICE_ACCOUNT_BASE64
    secretName: notification-firebase-secret
    secretKey: FIREBASE_SERVICE_ACCOUNT_BASE64
