secrets:
  existingSecretName: "postgresql-prod-secret"

replicaCount: 1

env:
  SPRING_PROFILES_ACTIVE: "prod"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

config:
  data:
    NOTIFICATION_CHANNEL_EMAIL_DAILY_LIMIT: "150"
    NOTIFICATION_CHANNEL_PUSH_DAILY_LIMIT: "5000"
    NOTIFICATION_DRIVER_RESET_PASSWORD_URL: "https://driver-portal.electrahub.net/reset-password"
