secrets:
  existingSecretName: "postgresql-dev-secret"

extraSecretEnv:
  - name: "APP_SECURITY_INTERNAL_TOKEN"
    secretName: "electrahub-internal-service-token"
    secretKey: "APP_SECURITY_INTERNAL_TOKEN"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
