replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "driver-portal-dev.example.com"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  path: /
  pathType: Prefix
  tls:
    enabled: false

hpa:
  enabled: false

pdb:
  enabled: false
