fullnameOverride: kafka

replicaCount: 1

image:
  repository: apache/kafka
  tag: "3.9.1"
  pullPolicy: IfNotPresent

clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
controllerQuorumVoters: "0@kafka-0.kafka-headless:9093"

service:
  clientPort: 9092
  controllerPort: 9093

persistence:
  storageClass: ""
  size: 10Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

topics:
  deviceEventsPartitions: 24
  lifecyclePartitions: 12
  deadLetterPartitions: 6
  replicationFactor: 1
  minInSyncReplicas: 1

pdb:
  enabled: false
  minAvailable: 1
