{{- if not .Values.auth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKeys.usernameKey }}: {{ .Values.auth.username | quote }}
    {{ .Values.auth.secretKeys.passwordKey }}: {{ required "auth.password is required when auth.existingSecretName is empty" .Values.auth.password | quote }}
    {{ .Values.auth.secretKeys.databaseKey }}: {{ .Values.auth.database | quote }}
  {{- end }}
