apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
          {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: {{ .Values.auth.secretKeys.usernameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "postgresql.fullname" .) .Values.auth.existingSecretName }}
                  key: {{ .Values.auth.secretKeys.usernameKey }}
            - name: {{ .Values.auth.secretKeys.passwordKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "postgresql.fullname" .) .Values.auth.existingSecretName }}
                  key: {{ .Values.auth.secretKeys.passwordKey }}
            - name: {{ .Values.auth.secretKeys.databaseKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "postgresql.fullname" .) .Values.auth.existingSecretName }}
                  key: {{ .Values.auth.secretKeys.databaseKey }}

          {{- if .Values.postgresql.config }}
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          {{- end }}

          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U ${{ .Values.auth.secretKeys.usernameKey }} -d ${{ .Values.auth.secretKeys.databaseKey }} -h 127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U ${{ .Values.auth.secretKeys.usernameKey }} -d ${{ .Values.auth.secretKeys.databaseKey }} -h 127.0.0.1"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

            {{- if .Values.postgresql.config }}
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            {{- end }}

            {{- if .Values.initdb.enabled }}
            - name: config
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}

      volumes:
        - name: config
          configMap:
            name: {{ include "postgresql.fullname" . }}-config

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "postgresql.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
