secrets:
  existingSecretName: "postgresql-prod-secret"

env:
  SPRING_PROFILES_ACTIVE: "prod"
  GRPC_SERVER_PORT: "-1"

extraSecretEnv:
  - name: "SPRING_DATA_REDIS_PASSWORD"
    secretName: "redis-prod-secret"
    secretKey: "redis-password"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
