secrets:
  existingSecretName: "postgresql-dev-secret"

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "payment-service-dev.electrahub.com"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
