secrets:
  existingSecretName: "postgresql-dev-secret"

extraSecretEnv:
  - name: "PAYMENT_GATEWAY_INTERNAL_TOKEN"
    secretName: "electrahub-internal-service-token"
    secretKey: "APP_SECURITY_INTERNAL_TOKEN"

config:
  data:
    PAYMENT_GATEWAY_CARD_ENROLLMENT_ENABLED: "true"
    PAYMENT_GATEWAY_EXECUTION_PILOT_NETWORK_IDS: "NW-EH-IND-DEMO"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_NETWORK_IDS: "NW-EH-IND-DEMO"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_SCOPES: "ENT-IN-DEMO|NW-EH-IND-DEMO|IN|INR"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
