secrets:
  existingSecretName: "postgresql-prod-secret"

extraSecretEnv:
  - name: "PAYMENT_GATEWAY_INTERNAL_TOKEN"
    secretName: "electrahub-internal-service-token"
    secretKey: "APP_SECURITY_INTERNAL_TOKEN"

env:
  SPRING_PROFILES_ACTIVE: "prod"

config:
  data:
    PAYMENT_GATEWAY_CARD_ENROLLMENT_ENABLED: "true"
    PAYMENT_GATEWAY_EXECUTION_PILOT_NETWORK_IDS: "NW-US-EAST-01,NW-US-WEST-01,NW-EH-USA-DEMO,NW-EH-IND-DEMO,NW-EH-EUR-DEMO"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_NETWORK_IDS: "NW-US-EAST-01,NW-US-WEST-01,NW-EH-USA-DEMO,NW-EH-IND-DEMO,NW-EH-EUR-DEMO"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_SCOPES: "ENT-US-DEV|NW-US-EAST-01|US|USD;ENT-US-DEV|NW-US-WEST-01|US|USD;ENT-US-DEV|NW-EH-USA-DEMO|US|USD;ENT-IN-DEMO|NW-EH-IND-DEMO|IN|INR;ENT-EU-DEV|NW-EH-EUR-DEMO|NL|EUR;ENT-EU-DEV|NW-EH-EUR-DEMO|DE|EUR"

podAnnotations:
  electrahub.net/payment-config-revision: "eu-stripe-enrollment-v2"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
