secrets:
  existingSecretName: "postgresql-prod-secret"

extraSecretEnv:
  - name: "PAYMENT_GATEWAY_INTERNAL_TOKEN"
    secretName: "electrahub-internal-service-token"
    secretKey: "APP_SECURITY_INTERNAL_TOKEN"

env:
  SPRING_PROFILES_ACTIVE: "prod"

config:
  data:
    PAYMENT_GATEWAY_CARD_ENROLLMENT_ENABLED: "true"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_NETWORK_IDS: "NW-US-EAST-01"
    PAYMENT_GATEWAY_CARD_ENROLLMENT_PILOT_SCOPES: "ENT-US-DEV|NW-US-EAST-01|US|USD"

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false
