apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver-portal-ui
  namespace: argocd
spec:
  project: amy
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: driver-portal-ui
      valueFiles:
        - driver-portal-ui/values.yaml
        - ../config/services/driver-portal-ui/us/values/dev-values.yaml
        - ../config/services/driver-portal-ui/us/version/dev-version.yaml
        - ../config/services/driver-portal-ui/us/base.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
