apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver-portal-ui-prod
  namespace: argocd
spec:
  project: electrahub-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: driver-portal-ui
      valueFiles:
        - driver-portal-ui/values.yaml
        - ../config/services/driver-portal-ui/us/base.yaml
        - ../config/services/driver-portal-ui/us/values/prod-values.yaml
        - ../config/services/driver-portal-ui/us/version/prod-version.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
