apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpp-simulator-prod
  namespace: argocd
spec:
  project: electrahub-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: ocpp-simulator
      valueFiles:
        - ocpp-simulator/values.yaml
        - ../config/services/ocpp-simulator/us/base.yaml
        - ../config/services/ocpp-simulator/us/values/prod-values.yaml
        - ../config/services/ocpp-simulator/us/version/prod-version.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
