apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpp-simulator-ui
  namespace: argocd
spec:
  project: amy
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: ocpp-simulator-ui
      valueFiles:
        - ocpp-simulator-ui/values.yaml
        - ../config/services/ocpp-simulator-ui/us/values/dev-values.yaml
        - ../config/services/ocpp-simulator-ui/us/version/dev-version.yaml
        - ../config/services/ocpp-simulator-ui/us/base.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
