apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-prod
  namespace: argocd
spec:
  project: electrahub-prod

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: infrastructure/prometheus
    helm:
      releaseName: prometheus
      valueFiles:
        - ../../platform-config/infrastructure/prometheus/us/values/prod.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true