apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-log-collector-prod
  namespace: argocd
spec:
  project: electrahub-prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: infrastructure/splunk-log-collector
    helm:
      releaseName: splunk-log-collector
      valueFiles:
        - ../../platform-config/infrastructure/splunk-log-collector/us/values/prod.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
