apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: electrahub-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: user-service
      valueFiles:
        - user-service/values.yaml
        - ../config/services/user-service/us/base.yaml
        - ../config/services/user-service/us/values/dev-values.yaml
        - ../config/services/user-service/us/version/dev-version.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
