apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-prod
  namespace: argocd
spec:
  project: electrahub-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: user-service
      valueFiles:
        - user-service/values.yaml
        - ../config/services/user-service/us/base.yaml
        - ../config/services/user-service/us/values/prod-values.yaml
        - ../config/services/user-service/us/version/prod-version.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
