apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-dev
  namespace: argocd
spec:
  project: electrahub-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: infrastructure/vllm
    helm:
      releaseName: vllm
      valueFiles:
        - values.yaml
        - ../../platform-config/infrastructure/vllm/us/values/dev.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
