apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-socket-connector-prod
  namespace: argocd
spec:
  project: electrahub-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/amolsurjuse/k8s-platform.git
    targetRevision: develop
    path: charts/common
    helm:
      releaseName: web-socket-connector
      valueFiles:
        - web-socket-connector/values.yaml
        - ../config/services/web-socket-connector/us/base.yaml
        - ../config/services/web-socket-connector/us/values/prod-values.yaml
        - ../config/services/web-socket-connector/us/version/prod-version.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
