replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: false
  className: "nginx"
  host: "ocpp-simulator-dev.electrahub.net"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  path: /(ocpp-simulator-ui/)?(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secretName: "electrahub-dev-tls"

hpa:
  enabled: false

pdb:
  enabled: false
