replicaCount: 2

resources:
  requests:
    cpu: "150m"
    memory: "192Mi"
  limits:
    cpu: "500m"
    memory: "768Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "ocpp-simulator-int.example.com"
  tls:
    enabled: false

hpa:
  enabled: false

pdb:
  enabled: false
