replicaCount: 2

resources:
  requests:
    cpu: "150m"
    memory: "192Mi"
  limits:
    cpu: "500m"
    memory: "768Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "ocpp-simulator-pi.electrahub.com"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$3"
  path: /(ocpp-simulator(-ui)?/)?(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: false

hpa:
  enabled: false

pdb:
  enabled: false
