replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "ocpp-simulator.electrahub.net"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$3"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  path: /(ocpp-simulator(-ui)?/)?(.*)
  pathType: ImplementationSpecific
  tls:
    enabled: true
    secretName: "electrahub-prod-tls"

hpa:
  enabled: false

pdb:
  enabled: false

metrics:
  servicemonitor:
    enabled: false

extraIngresses:
  - name: api
    fullname: ocpp-simulator-api
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    rules:
      - host: "ocpp-simulator.electrahub.net"
        paths:
          - path: /(api(?:/.*)?|ocpp(?:/.*)?|ws(?:/.*)?|healthz|readyz)
            pathType: ImplementationSpecific
            serviceName: ocpp-simulator
            servicePort: 8081
    tls:
      - hosts:
          - "ocpp-simulator.electrahub.net"
        secretName: "electrahub-prod-tls"
